<?php
include("main.php");
include("config/database.php");
include("function/delete_user.php");
include("function/save_new_user.php");
include("function/save_edit.php");
include("singin.php");
include("singup.php");
?>